require 'pry'
require 'faker'
require 'yaml/store'
require 'date'

require_relative 'modules/errors'
require_relative 'modules/validation'
require_relative 'modules/data_loader'
require_relative 'entities/author'
require_relative 'entities/book'
require_relative 'entities/reader'
require_relative 'entities/order'
require_relative 'services/data_generator'
require_relative 'modules/statistics'
require_relative 'entities/library'
require_relative 'modules/constants'
